/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package answer;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import question.QuestionManager;
import question.Questions;

/**
 *
 * @author WOLF
 */
public class ManageAnswer extends javax.swing.JDialog {

    CallbackAnswer callbackAnswer;

    public interface CallbackAnswer {

        public void actionloadAnswer();
    }
    
    /**
     * Creates new form ManageAnswers
     */
    public ManageAnswer(java.awt.Frame parent, boolean modal, CallbackAnswer callbackAnswer) {
        super(parent, modal);
        initComponents();
        this.callbackAnswer = callbackAnswer;
        loadQuestion();
        loadImg();
    }
    
    public void loadImg() {
        ImageIcon b1 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../image/cancel.png")));
        Image iB1 = b1.getImage();
        Image img1 = iB1.getScaledInstance(50, 40, Image.SCALE_SMOOTH);
        ImageIcon ic1 = new ImageIcon(img1);
        buttonCancel.setIcon(ic1);
        ImageIcon b2 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../image/updateQues.png")));
        Image iB2 = b2.getImage();
        Image img2 = iB2.getScaledInstance(50, 40, Image.SCALE_SMOOTH);
        ImageIcon ic2 = new ImageIcon(img2);
        buttonUpdateAnswer.setIcon(ic2);
        ImageIcon b3 = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../image/addQues.png")));
        Image iB3 = b3.getImage();
        Image img3 = iB3.getScaledInstance(50, 40, Image.SCALE_SMOOTH);
        ImageIcon ic3 = new ImageIcon(img3);
        buttonAddAnswer.setIcon(ic3);
    }

    public void loadQuestion() {
        QuestionManager qm = new QuestionManager();
        cbxQuestion.setModel(qm.getQuestion());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupResult = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        rdbTrue = new javax.swing.JRadioButton();
        rdbFalse = new javax.swing.JRadioButton();
        buttonAddAnswer = new javax.swing.JButton();
        buttonUpdateAnswer = new javax.swing.JButton();
        buttonCancel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblFieldId = new javax.swing.JLabel();
        cbxQuestion = new javax.swing.JComboBox<>();
        lblId = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaAnswer = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel3.setText("Result:");

        buttonGroupResult.add(rdbTrue);
        rdbTrue.setText("True");

        buttonGroupResult.add(rdbFalse);
        rdbFalse.setText("False");

        buttonAddAnswer.setText("Add");
        buttonAddAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddAnswerActionPerformed(evt);
            }
        });

        buttonUpdateAnswer.setText("Update");
        buttonUpdateAnswer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateAnswerActionPerformed(evt);
            }
        });

        buttonCancel.setText("Cancel");
        buttonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelActionPerformed(evt);
            }
        });

        jLabel1.setText("Question:");

        lblFieldId.setText("Id:");

        jLabel2.setText("Answer:");

        txaAnswer.setColumns(20);
        txaAnswer.setRows(5);
        jScrollPane1.setViewportView(txaAnswer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbxQuestion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdbTrue)
                        .addGap(18, 18, 18)
                        .addComponent(rdbFalse)
                        .addGap(18, 18, 18)
                        .addComponent(lblFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 228, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonUpdateAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonAddAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxQuestion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rdbTrue)
                    .addComponent(rdbFalse)
                    .addComponent(lblFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAddAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonUpdateAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddAnswerActionPerformed
        // TODO add your handling code here:
        String answer = txaAnswer.getText();
        int questionId = ((Questions) cbxQuestion.getSelectedItem()).getId();
        int result = rdbTrue.isSelected() ? 1 : 0;

        if (answer.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Please enter answer");
        } else if (buttonGroupResult.getSelection() == null) {
            JOptionPane.showMessageDialog(rootPane, "Please choose result");
        } else {
            AnswerManager am = new AnswerManager();
            Answer a = new Answer(answer, result, questionId);
            int row = am.createAnswer(a);
            if (row == 0) {
                JOptionPane.showMessageDialog(rootPane, "Add answer success");
                callbackAnswer.actionloadAnswer();
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(rootPane, "Add answer fail, please try again!!!");
            }
        }
    }//GEN-LAST:event_buttonAddAnswerActionPerformed

    private void buttonUpdateAnswerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateAnswerActionPerformed
        // TODO add your handling code here:
        String answer = txaAnswer.getText();
        int questionId = ((Questions) cbxQuestion.getSelectedItem()).getId();
        int result = rdbTrue.isSelected() ? 1 : 0;
        int id = Integer.parseInt(lblId.getText());

        if (answer.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Please enter answer");
        } else if (buttonGroupResult.getSelection() == null) {
            JOptionPane.showMessageDialog(rootPane, "Please choose result");
        } else {
            int choose = JOptionPane.showConfirmDialog(rootPane, "Are you sure want to update this answer?", "Message", JOptionPane.OK_CANCEL_OPTION);
            if (choose == JOptionPane.OK_OPTION) {
                AnswerManager am = new AnswerManager();
                Answer a = new Answer(id, answer, result, questionId);
                int row = am.updateAnswer(a);
                if (row == 0) {
                    JOptionPane.showMessageDialog(rootPane, "Update answer success");
                    callbackAnswer.actionloadAnswer();
                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Update answer fail, please try again!!!");
                }
            }
        }
    }//GEN-LAST:event_buttonUpdateAnswerActionPerformed

    private void buttonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_buttonCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageAnswer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageAnswer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageAnswer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageAnswer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManageAnswer dialog = new ManageAnswer(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton buttonAddAnswer;
    private javax.swing.JButton buttonCancel;
    private javax.swing.ButtonGroup buttonGroupResult;
    public static javax.swing.JButton buttonUpdateAnswer;
    public static javax.swing.JComboBox<Questions> cbxQuestion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblFieldId;
    public static javax.swing.JLabel lblId;
    public static javax.swing.JRadioButton rdbFalse;
    public static javax.swing.JRadioButton rdbTrue;
    public static javax.swing.JTextArea txaAnswer;
    // End of variables declaration//GEN-END:variables
}
